/* GENERATED by scripts/dev.mjs on every `npm run dev` — do not edit by hand.
   Tells js/api.js which backend this local run is using. Committed with a
   sensible default so the site also works when served by another tool. */
window.CYBERYARDHUB_API_BASE_URL = 'http://localhost:4001/api';
